version: "3.8"

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: ft_transcendence
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  web:
    build: ./BE
    env_file:
      - .env
    environment:
      DB_HOST: db
      GANACHE_HTTP: http://host.docker.internal:8545
      GANACHE_ACCOUNT: ${GANACHE_ACCOUNT}
      GANACHE_KEY: ${GANACHE_KEY}
    command: python manage.py runsslserver 0.0.0.0:443 --certificate /app/django.crt --key /app/django.key
    volumes:
      - ./BE:/app
    working_dir: /app
    ports:
      - "8000:443"
    depends_on:
      - db

  frontend:
    build: ./FE/.
    image: nginx:1.0
    container_name: frontend
    volumes:
      - ./FE:/usr/share/nginx/html
    ports:
      - "443:443"  

volumes:
  pg_data:
