version: "3.8"

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: ft_transcendence
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  web:
    build: ./BE
    environment:
      GANACHE_HTTP: http://host.docker.internal:8545
      GANACHE_ACCOUNT: 0x90F8bf6A479f320ead074411a4B0e7944Ea8c9C1
      GANACHE_KEY: 0x4f3edf983ac636a65a842ce7c78d9aa706d3b113bce9c46f30d7d21715b23b1d
    command: python manage.py runserver 0.0.0.0:443
    volumes:
      - ./BE:/app
    working_dir: /app
    ports:
      - "8000:443"
    depends_on:
      - db

  frontend:
    build: ./FE/.
    image: nginx:1.0
    container_name: frontend
    volumes:
      - ./FE:/usr/share/nginx/html
    ports:
      - "443:443"  

volumes:
  pg_data:
