version: "3.8"

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: ft_transcendence
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  web:
    build: ./BE
    command: python manage.py runserver 0.0.0.0:443
    volumes:
      - ./BE:/app
    working_dir: /app
    ports:
      - "8000:443"
    depends_on:
      - db

  frontend:
    build: ./FE/.
    image: nginx:1.0
    container_name: frontend
    volumes:
      - ./FE:/usr/share/nginx/html
    ports:
      - "443:443"  

volumes:
  pg_data:
