version: '3'

services:
  user-service:
    build: ./BE/user_service
    ports:
      - "8000:8000"
    networks:
      - backend-network

  game-service:
    build: ./BE/game_service
    ports:
      - "8001:8001"
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
